default:
  db_host: "35.243.133.29"
  db_port: 5432
  db_user: "postgres"
  db_timeout: 30
  service_tier: "standard"
  flex_timeout: 180

test:
  db_name: "sragent-test"
  models:
    default: "o4-mini"
    esearch: "gpt-4.1-mini"
    esummary: "gpt-4.1-mini"
    elink: "gpt-4.1-mini"
    efetch: "gpt-4.1-mini"
    sequences: "gpt-4.1-mini"
    ncbi_fetch: "o4-mini"
    bigquery: "o4-mini"
    entrez: "o4-mini"
    sragent: "o4-mini"
    tissue_ontology: "o4-mini"
    metadata: "gpt-4.1"
    metadata_router: "o4-mini"
    convert_router: "gpt-4.1-mini"
    accessions: "gpt-4.1-mini"
    entrez_convert: "gpt-4.1-mini"
    find_datasets: "gpt-4.1-mini"
    step_summary: "gpt-4.1-mini"
    get_entrez_ids: "gpt-4.1-mini"
    gemini_default: "gemini-pro" # Added for flexibility
    gemini_test_agent: "gemini-pro" # For testing specific gemini loading
  temperature:
    default: 0.1
    esearch: 0.1
    esummary: 0.1
    elink: 0.1
    efetch: 0.1
    sequences: 0.1
    ncbi_fetch: 0.1
    bigquery: 0.1
    entrez: 0.1
    sragent: 0.1
    tissue_ontology: 0.1
    metadata: 0.1
    convert_router: 0.1
    metadata_router: 0.1
    accessions: 0.1
    entrez_convert: 0.1
    find_datasets: 0.1
    step_summary: 0.1
    get_entrez_ids: 0.0
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "low"
    entrez: "low"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "medium"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "low"
    find_datasets: "low"
    step_summary: ""
    get_entrez_ids: "low"
  service_tier:
    default: "flex"
    gemini_test_agent: "default" # Gemini doesn't use flex
    esearch: "default"
    esummary: "default"
    elink: "default"
    efetch: "default"
    sequences: "default"
    ncbi_fetch: "flex"
    bigquery: "flex"
    entrez: "flex"
    sragent: "flex"
    tissue_ontology: "flex"
    metadata: "default"
    metadata_router: "flex"
    convert_router: "default"
    accessions: "default"
    entrez_convert: "default"
    find_datasets: "default"
    step_summary: "default"
    get_entrez_ids: "default"
    
prod:
  db_name: "sragent-prod"
  models:
    default: "o4-mini"
    esearch: "gpt-4.1-mini"
    esummary: "gpt-4.1-mini"
    elink: "gpt-4.1-mini"
    efetch: "gpt-4.1-mini"
    sequences: "gpt-4.1-mini"
    ncbi_fetch: "o4-mini"
    bigquery: "o4-mini"
    entrez: "o4-mini"
    sragent: "o4-mini"
    tissue_ontology: "o4-mini"
    metadata: "gpt-4.1"
    metadata_router: "o4-mini"
    convert_router: "gpt-4.1-mini"
    accessions: "gpt-4.1-mini"
    entrez_convert: "gpt-4.1-mini"
    find_datasets: "gpt-4.1-mini"
    step_summary: "gpt-4.1-mini"
    get_entrez_ids: "gpt-4.1-mini"
    gemini_default: "gemini-pro" # Added for flexibility
  temperature:
    default: 0.1
    esearch: 0.1
    esummary: 0.1
    elink: 0.1
    efetch: 0.1
    sequences: 0.1
    ncbi_fetch: 0.1
    bigquery: 0.1
    entrez: 0.1
    sragent: 0.1
    tissue_ontology: 0.1
    metadata: 0.1
    convert_router: 0.1
    metadata_router: 0.1
    accessions: 0.1
    entrez_convert: 0.1
    find_datasets: 0.1
    step_summary: 0.1
    get_entrez_ids: 0.0
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "low"
    entrez: "low"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "medium"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "low"
    find_datasets: "low"
    step_summary: ""
    get_entrez_ids: "low"
  service_tier:
    default: "flex"
    esearch: "default"
    esummary: "default"
    elink: "default"
    efetch: "default"
    sequences: "default"
    ncbi_fetch: "flex"
    bigquery: "flex"
    entrez: "flex"
    sragent: "flex"
    tissue_ontology: "flex"
    metadata: "default"
    metadata_router: "flex"
    convert_router: "default"
    accessions: "default"
    entrez_convert: "default"
    find_datasets: "default"
    step_summary: "default"
    get_entrez_ids: "default"
  
claude:
  db_name: "sragent-test"
  models:
    default: "claude-sonnet-4-0"
  temperature:
    default: 0.1
  reasoning_effort:
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "medium"
    entrez: "medium"
    sragent: "medium"
    tissue_ontology: ""
    metadata: "high"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "medium"
    find_datasets: "medium"
    step_summary: ""
  service_tier:
    default: "default"

gemini:
  db_name: "sragent-test" # Assuming similar DB needs as test for now
  models:
    default: "gemini-pro" # Or other appropriate Gemini model
    esearch: "gemini-pro"
    esummary: "gemini-pro"
    elink: "gemini-pro"
    efetch: "gemini-pro"
    sequences: "gemini-pro"
    ncbi_fetch: "gemini-pro"
    bigquery: "gemini-pro"
    entrez: "gemini-pro"
    sragent: "gemini-pro"
    tissue_ontology: "gemini-pro"
    metadata: "gemini-pro" # Or a more capable version if needed
    metadata_router: "gemini-pro"
    convert_router: "gemini-pro"
    accessions: "gemini-pro"
    entrez_convert: "gemini-pro"
    find_datasets: "gemini-pro"
    step_summary: "gemini-pro"
    get_entrez_ids: "gemini-pro"
  temperature:
    default: 0.1 # Adjust as needed for Gemini models
    # Add specific temperatures if Gemini models behave differently
  reasoning_effort: # Gemini models might not use this, or use it differently. Adjust as needed.
    default: "low"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "medium"
    metadata_router: "medium"
  service_tier: # Gemini might not have service tiers like OpenAI. Defaulting.
    default: "default"
